<?php

namespace ContainerX2evnbX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBlogTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\BlogType' shared autowired service.
     *
     * @return \App\Form\BlogType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/BlogType.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/DataTransformerInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Form/DataTransformer/TagTransformer.php';

        return $container->privates['App\\Form\\BlogType'] = new \App\Form\BlogType(new \App\Form\DataTransformer\TagTransformer(($container->privates['App\\Repository\\TagRepository'] ?? $container->load('getTagRepositoryService'))), ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService')));
    }
}
