<?php

namespace ContainerX2evnbX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContentWatchApiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\ContentWatchApi' shared autowired service.
     *
     * @return \App\Service\ContentWatchApi
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/ContentWatchApi.php';

        return $container->privates['App\\Service\\ContentWatchApi'] = new \App\Service\ContentWatchApi($container->getEnv('CONTENT_WATCH_API_KEY'));
    }
}
