<?php

namespace ContainerXuDc46M;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IxWdBBFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ixWdBBF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ixWdBBF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\Admin\\BlogController::index' => ['privates', '.service_locator.US_4TLn', 'get_ServiceLocator_US4TLnService', true],
            'App\\Controller\\Admin\\BlogController::new' => ['privates', '.service_locator.gLIleFa', 'get_ServiceLocator_GLIleFaService', true],
            'App\\Controller\\Admin\\BlogController::show' => ['privates', '.service_locator..TQcBti', 'get_ServiceLocator__TQcBtiService', true],
            'App\\Controller\\Admin\\BlogController::edit' => ['privates', '.service_locator.wVePTfL', 'get_ServiceLocator_WVePTfLService', true],
            'App\\Controller\\Admin\\BlogController::delete' => ['privates', '.service_locator.wVePTfL', 'get_ServiceLocator_WVePTfLService', true],
            'App\\Controller\\Admin\\CategoryController::index' => ['privates', '.service_locator.3opkxl5', 'get_ServiceLocator_3opkxl5Service', true],
            'App\\Controller\\Admin\\CategoryController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\Admin\\CategoryController::show' => ['privates', '.service_locator.8IESKP1', 'get_ServiceLocator_8IESKP1Service', true],
            'App\\Controller\\Admin\\CategoryController::edit' => ['privates', '.service_locator.WoAniWU', 'get_ServiceLocator_WoAniWUService', true],
            'App\\Controller\\Admin\\CategoryController::delete' => ['privates', '.service_locator.WoAniWU', 'get_ServiceLocator_WoAniWUService', true],
            'App\\Controller\\BlogController::index' => ['privates', '.service_locator.US_4TLn', 'get_ServiceLocator_US4TLnService', true],
            'App\\Controller\\BlogController::new' => ['privates', '.service_locator.PcrcuR4', 'get_ServiceLocator_PcrcuR4Service', true],
            'App\\Controller\\BlogController::show' => ['privates', '.service_locator.wVePTfL', 'get_ServiceLocator_WVePTfLService', true],
            'App\\Controller\\BlogController::edit' => ['privates', '.service_locator.wVePTfL', 'get_ServiceLocator_WVePTfLService', true],
            'App\\Controller\\BlogController::delete' => ['privates', '.service_locator.wVePTfL', 'get_ServiceLocator_WVePTfLService', true],
            'App\\Controller\\HomePageController::index' => ['privates', '.service_locator.OiOHUjB', 'get_ServiceLocator_OiOHUjBService', true],
            'App\\Controller\\HomePageController::indexBlogs' => ['privates', '.service_locator.US_4TLn', 'get_ServiceLocator_US4TLnService', true],
            'App\\Controller\\LoginController::index' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\LoginController::redirectLogin' => ['privates', '.service_locator.ATt7aga', 'get_ServiceLocator_ATt7agaService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.jUlH1E8', 'get_ServiceLocator_JUlH1E8Service', true],
            'App\\Controller\\UserController::index' => ['privates', '.service_locator.kPUOGb8', 'get_ServiceLocator_KPUOGb8Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\Admin\\BlogController:index' => ['privates', '.service_locator.US_4TLn', 'get_ServiceLocator_US4TLnService', true],
            'App\\Controller\\Admin\\BlogController:new' => ['privates', '.service_locator.gLIleFa', 'get_ServiceLocator_GLIleFaService', true],
            'App\\Controller\\Admin\\BlogController:show' => ['privates', '.service_locator..TQcBti', 'get_ServiceLocator__TQcBtiService', true],
            'App\\Controller\\Admin\\BlogController:edit' => ['privates', '.service_locator.wVePTfL', 'get_ServiceLocator_WVePTfLService', true],
            'App\\Controller\\Admin\\BlogController:delete' => ['privates', '.service_locator.wVePTfL', 'get_ServiceLocator_WVePTfLService', true],
            'App\\Controller\\Admin\\CategoryController:index' => ['privates', '.service_locator.3opkxl5', 'get_ServiceLocator_3opkxl5Service', true],
            'App\\Controller\\Admin\\CategoryController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\Admin\\CategoryController:show' => ['privates', '.service_locator.8IESKP1', 'get_ServiceLocator_8IESKP1Service', true],
            'App\\Controller\\Admin\\CategoryController:edit' => ['privates', '.service_locator.WoAniWU', 'get_ServiceLocator_WoAniWUService', true],
            'App\\Controller\\Admin\\CategoryController:delete' => ['privates', '.service_locator.WoAniWU', 'get_ServiceLocator_WoAniWUService', true],
            'App\\Controller\\BlogController:index' => ['privates', '.service_locator.US_4TLn', 'get_ServiceLocator_US4TLnService', true],
            'App\\Controller\\BlogController:new' => ['privates', '.service_locator.PcrcuR4', 'get_ServiceLocator_PcrcuR4Service', true],
            'App\\Controller\\BlogController:show' => ['privates', '.service_locator.wVePTfL', 'get_ServiceLocator_WVePTfLService', true],
            'App\\Controller\\BlogController:edit' => ['privates', '.service_locator.wVePTfL', 'get_ServiceLocator_WVePTfLService', true],
            'App\\Controller\\BlogController:delete' => ['privates', '.service_locator.wVePTfL', 'get_ServiceLocator_WVePTfLService', true],
            'App\\Controller\\HomePageController:index' => ['privates', '.service_locator.OiOHUjB', 'get_ServiceLocator_OiOHUjBService', true],
            'App\\Controller\\HomePageController:indexBlogs' => ['privates', '.service_locator.US_4TLn', 'get_ServiceLocator_US4TLnService', true],
            'App\\Controller\\LoginController:index' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\LoginController:redirectLogin' => ['privates', '.service_locator.ATt7aga', 'get_ServiceLocator_ATt7agaService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.jUlH1E8', 'get_ServiceLocator_JUlH1E8Service', true],
            'App\\Controller\\UserController:index' => ['privates', '.service_locator.kPUOGb8', 'get_ServiceLocator_KPUOGb8Service', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\Admin\\BlogController::index' => '?',
            'App\\Controller\\Admin\\BlogController::new' => '?',
            'App\\Controller\\Admin\\BlogController::show' => '?',
            'App\\Controller\\Admin\\BlogController::edit' => '?',
            'App\\Controller\\Admin\\BlogController::delete' => '?',
            'App\\Controller\\Admin\\CategoryController::index' => '?',
            'App\\Controller\\Admin\\CategoryController::new' => '?',
            'App\\Controller\\Admin\\CategoryController::show' => '?',
            'App\\Controller\\Admin\\CategoryController::edit' => '?',
            'App\\Controller\\Admin\\CategoryController::delete' => '?',
            'App\\Controller\\BlogController::index' => '?',
            'App\\Controller\\BlogController::new' => '?',
            'App\\Controller\\BlogController::show' => '?',
            'App\\Controller\\BlogController::edit' => '?',
            'App\\Controller\\BlogController::delete' => '?',
            'App\\Controller\\HomePageController::index' => '?',
            'App\\Controller\\HomePageController::indexBlogs' => '?',
            'App\\Controller\\LoginController::index' => '?',
            'App\\Controller\\LoginController::redirectLogin' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\UserController::index' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\Admin\\BlogController:index' => '?',
            'App\\Controller\\Admin\\BlogController:new' => '?',
            'App\\Controller\\Admin\\BlogController:show' => '?',
            'App\\Controller\\Admin\\BlogController:edit' => '?',
            'App\\Controller\\Admin\\BlogController:delete' => '?',
            'App\\Controller\\Admin\\CategoryController:index' => '?',
            'App\\Controller\\Admin\\CategoryController:new' => '?',
            'App\\Controller\\Admin\\CategoryController:show' => '?',
            'App\\Controller\\Admin\\CategoryController:edit' => '?',
            'App\\Controller\\Admin\\CategoryController:delete' => '?',
            'App\\Controller\\BlogController:index' => '?',
            'App\\Controller\\BlogController:new' => '?',
            'App\\Controller\\BlogController:show' => '?',
            'App\\Controller\\BlogController:edit' => '?',
            'App\\Controller\\BlogController:delete' => '?',
            'App\\Controller\\HomePageController:index' => '?',
            'App\\Controller\\HomePageController:indexBlogs' => '?',
            'App\\Controller\\LoginController:index' => '?',
            'App\\Controller\\LoginController:redirectLogin' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\UserController:index' => '?',
        ]);
    }
}
