<?php

namespace ContainerXuDc46M;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_F9tC4zXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.messenger.handler_descriptor.F9tC4zX' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlerDescriptor.php';
        include_once \dirname(__DIR__, 4).'/src/MessageHandler/ContentWatchHandler.php';
        include_once \dirname(__DIR__, 4).'/src/Service/ContentWatchApi.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['.messenger.handler_descriptor.F9tC4zX'])) {
            return $container->privates['.messenger.handler_descriptor.F9tC4zX'];
        }

        return $container->privates['.messenger.handler_descriptor.F9tC4zX'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(new \App\MessageHandler\ContentWatchHandler(($container->privates['App\\Service\\ContentWatchApi'] ??= new \App\Service\ContentWatchApi($container->getEnv('CONTENT_WATCH_API_KEY'))), $a, ($container->privates['App\\Repository\\BlogRepository'] ?? $container->load('getBlogRepositoryService'))), []);
    }
}
