<?php

namespace ContainerXuDc46M;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGismeteoApiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\GismeteoApi' shared autowired service.
     *
     * @return \App\Service\GismeteoApi
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/GismeteoApi.php';

        return $container->privates['App\\Service\\GismeteoApi'] = new \App\Service\GismeteoApi($container->getEnv('GISMETEO_API_KEY'));
    }
}
