<?php

namespace ContainerXuDc46M;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUnsplashServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\UnsplashService' shared autowired service.
     *
     * @return \App\Service\UnsplashService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/UnsplashService.php';

        return $container->privates['App\\Service\\UnsplashService'] = new \App\Service\UnsplashService(($container->privates['.debug.http_client'] ?? self::get_Debug_HttpClientService($container)), $container->getEnv('UNSPLASH_API_KEY'));
    }
}
